import type { CaptionPreset, CaptionStyle } from "./types";

const base: CaptionStyle = {
  fontFamily: "Inter",
  fontWeight: 800,
  italic: false,
  fontSize: 0.062,
  uppercase: false,
  letterSpacing: 0,
  lineHeight: 1.18,
  textColor: "#FFFFFF",
  activeColor: "#C6F24E",
  activeBg: null,
  blockBg: null,
  blockPadding: 0.02,
  blockRadius: 0.02,
  strokeColor: "#000000",
  strokeWidth: 0.1,
  shadowColor: "rgba(0,0,0,0.55)",
  shadowBlur: 0.18,
  shadowOffsetY: 0.05,
  animation: "word",
  blockAnimation: "none",
  highlight: "color",
  positionY: 0.74,
  maxWidth: 0.84,
  wordsPerBlock: 4,
  align: "center",
};

function preset(
  id: string,
  name: string,
  group: CaptionPreset["group"],
  style: Partial<CaptionStyle>,
): CaptionPreset {
  return { id, name, group, style: { ...base, ...style } };
}

export const CAPTION_PRESETS: CaptionPreset[] = [
  preset("hormozi", "Hormozi Pop", "Trending", {
    fontFamily: "Montserrat",
    fontWeight: 900,
    uppercase: true,
    fontSize: 0.072,
    activeColor: "#FFE01B",
    animation: "pop",
    highlight: "color",
    strokeWidth: 0.14,
    wordsPerBlock: 3,
  }),
  preset("beast", "Impact Beast", "Bold", {
    fontFamily: "Anton",
    fontWeight: 400,
    uppercase: true,
    fontSize: 0.084,
    letterSpacing: 0.01,
    activeColor: "#FF3B30",
    animation: "shake",
    strokeWidth: 0.15,
    wordsPerBlock: 3,
  }),
  preset("word-box", "Word Box", "Trending", {
    fontFamily: "Inter",
    fontWeight: 900,
    uppercase: true,
    fontSize: 0.058,
    textColor: "#FFFFFF",
    activeColor: "#0B0B0F",
    activeBg: "#C6F24E",
    highlight: "box",
    animation: "word",
    strokeWidth: 0.08,
    wordsPerBlock: 4,
  }),
  preset("tiktok", "TikTok Block", "Clean", {
    fontFamily: "Inter",
    fontWeight: 700,
    fontSize: 0.05,
    textColor: "#FFFFFF",
    blockBg: "rgba(0,0,0,0.72)",
    animation: "none",
    strokeWidth: 0,
    shadowBlur: 0.08,
    wordsPerBlock: 7,
    positionY: 0.8,
  }),
  preset("typewriter", "Typewriter", "Editorial", {
    fontFamily: "JetBrains Mono",
    fontWeight: 700,
    fontSize: 0.046,
    letterSpacing: 0.01,
    animation: "typewriter",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    strokeWidth: 0.06,
    wordsPerBlock: 6,
  }),
  preset("fade-soft", "Soft Fade", "Clean", {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: 0.046,
    animation: "fade",
    textColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    strokeWidth: 0,
    shadowBlur: 0.22,
    wordsPerBlock: 6,
    letterSpacing: 0.005,
  }),
  preset("bounce", "Bounce Pop", "Playful", {
    fontFamily: "Poppins",
    fontWeight: 800,
    fontSize: 0.066,
    animation: "bounce",
    activeColor: "#FF7AC8",
    strokeWidth: 0.12,
    wordsPerBlock: 3,
  }),
  preset("slide-up", "Slide Up", "Clean", {
    fontFamily: "Space Grotesk",
    fontWeight: 700,
    fontSize: 0.05,
    animation: "slide",
    activeColor: "#FFFFFF",
    textColor: "#FFFFFF",
    strokeWidth: 0.05,
    wordsPerBlock: 6,
  }),
  preset("flip", "Flip In", "Playful", {
    fontFamily: "Montserrat",
    fontWeight: 900,
    uppercase: true,
    fontSize: 0.062,
    animation: "flip",
    activeColor: "#FFD166",
    strokeWidth: 0.12,
    wordsPerBlock: 3,
  }),
  preset("underline", "Underline Beat", "Trending", {
    fontFamily: "Inter",
    fontWeight: 800,
    fontSize: 0.054,
    highlight: "underline",
    animation: "word",
    activeColor: "#C6F24E",
    strokeWidth: 0.08,
    wordsPerBlock: 5,
  }),
  preset("scale-focus", "Scale Focus", "Bold", {
    fontFamily: "Archivo Black",
    fontWeight: 400,
    uppercase: true,
    fontSize: 0.058,
    highlight: "scale",
    animation: "word",
    textColor: "rgba(255,255,255,0.55)",
    activeColor: "#FFFFFF",
    strokeWidth: 0.1,
    wordsPerBlock: 4,
  }),
  preset("neon", "Neon Glow", "Playful", {
    fontFamily: "Poppins",
    fontWeight: 800,
    uppercase: true,
    fontSize: 0.058,
    textColor: "#FFFFFF",
    activeColor: "#4FD1FF",
    strokeWidth: 0.04,
    shadowColor: "rgba(79,209,255,0.85)",
    shadowBlur: 0.5,
    shadowOffsetY: 0,
    animation: "word",
    wordsPerBlock: 4,
  }),
  preset("minimal", "Minimal Line", "Editorial", {
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: 0.038,
    letterSpacing: 0.02,
    uppercase: true,
    animation: "none",
    strokeWidth: 0,
    shadowBlur: 0.2,
    wordsPerBlock: 8,
    positionY: 0.86,
  }),
  preset("serif-doc", "Documentary", "Editorial", {
    fontFamily: "Space Grotesk",
    fontWeight: 500,
    fontSize: 0.042,
    animation: "fade",
    textColor: "#F5F1EA",
    activeColor: "#F5F1EA",
    blockBg: "rgba(11,11,15,0.62)",
    strokeWidth: 0,
    wordsPerBlock: 8,
    positionY: 0.84,
  }),
  preset("yellow-classic", "Classic Yellow", "Clean", {
    fontFamily: "Inter",
    fontWeight: 800,
    fontSize: 0.05,
    textColor: "#FFE01B",
    activeColor: "#FFFFFF",
    animation: "none",
    strokeWidth: 0.12,
    wordsPerBlock: 7,
    positionY: 0.82,
  }),
  preset("stacked", "Stacked Bold", "Bold", {
    fontFamily: "Anton",
    fontWeight: 400,
    uppercase: true,
    fontSize: 0.09,
    lineHeight: 1.02,
    maxWidth: 0.6,
    activeColor: "#C6F24E",
    animation: "pop",
    strokeWidth: 0.12,
    wordsPerBlock: 2,
    positionY: 0.7,
  }),
  preset("podcast-pill", "Podcast Pill", "Trending", {
    fontFamily: "Jost",
    fontWeight: 900,
    fontSize: 0.058,
    lineHeight: 1.12,
    uppercase: false,
    textColor: "#FFFFFF",
    activeColor: "#FFEA00",
    highlight: "color",
    // instant snap to yellow while spoken — no scale, no bounce
    animation: "word",
    blockAnimation: "none",
    blockBg: "#000000",
    // padding relative to font size: 35% vertical, 50% horizontal
    blockPadding: 0.058 * 0.35,
    blockPaddingX: 0.058 * 0.5,
    blockPaddingXRatio: 0.5 / 0.35,
    // corner radius = 25% of font size
    blockRadius: 0.058 * 0.25,
    strokeColor: "transparent",
    strokeWidth: 0,
    shadowColor: "rgba(0,0,0,0)",
    shadowBlur: 0,
    shadowOffsetY: 0,
    letterSpacing: 0,
    wordsPerBlock: 2,
    maxWidth: 0.74,
    positionY: 0.74,
  }),

];

export const DEFAULT_PRESET_ID = "hormozi";

export const FONT_OPTIONS = [
  "Inter",
  "Jost",
  "Montserrat",
  "Poppins",
  "Anton",
  "Archivo Black",
  "Bebas Neue",
  "Space Grotesk",
  "JetBrains Mono",
  "Rubik",
];
